### ISSUE TITLE
3.3. Selecting a specific JDK on Red Hat Enterprise Linux per application

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#22] opened 2019-06-11 12:30 UTC
QE by @judovana  

3.3. Selecting a specific JDK on Red Hat Enterprise Linux per application

Have multiple JDKs installed - does not work 

$ JAVA_HOME=/usr/lib/jvm/java-11-openjdk mvn --version 
This command should probably be two lines
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 11.0.3, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-11.0.3.7-0.el7_6.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.21.2.el7.x86_64", arch: "amd64", family: "unix"
$ JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk mvn --version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.21.2.el7.x86_64", arch: "amd64", family: "unix"

Why is there ORACLE Java as an example here? Like seriously, this is an article about OpenJDK and you put Oracle binaries there as an example?

**Comment by jerboaa** [comment] 2019-06-17 08:24
@ncbaratta I don't get this issue. What makes the reporter think this is Oracle Java? `/usr/lib/jvm/java-11-openjdk` and `/usr/lib/jvm/java-1.8.0-openjdk` are directories owned by the `java-11-openjdk` and `java-1.8.0-openjdk` RPM packages. Red Hat builds of OpenJDK don't change the vendor property if that's the issue.

**Comment by pmikova** [comment] 2019-06-17 10:22
I rechecked and cleared out with jvanek, turns out I was calling the command --version wrongly, and did not know we use Oracle in our vendor property, sorry about that. The second part of the issue is therefore invalid.
Thanks!

**Comment by jerboaa** [comment] 2019-06-17 13:45
> 3.3. Selecting a specific JDK on Red Hat Enterprise Linux per application
> 
> Have multiple JDKs installed - does not work

@pmikova  I take it this "does not work" is in relation to the hyperlink target as well?

**Comment by pmikova** [comment] 2019-06-17 13:47
Yes, you can take this for all occurrences in the doc, most of the links that were pointing on article parts were not working.

**Comment by jerboaa** [comment] 2019-06-17 16:55
Closing as a duplicate of #33

**Closed as completed by jerboaa** 2019-06-17 16:55 UTC
