### ISSUE TITLE
3.4. Selecting a specific JDK on Red Hat Enterprise Linux installed using ZIP bundles

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#23] opened 2019-06-11 12:30 UTC
QE by @judovana  

3.4. Selecting a specific JDK on Red Hat Enterprise Linux installed using ZIP bundles

Are you sure about the zip bundles? Linux usually uses tarballs…

Step 2:

You are once again appending it to the path (therefore if there is any other JDK or customer added any other JDK on path before doing this (as said in the manual), this will not work. You have to put it at the beginning, but I don’t like the idea that customers will mess with the PATH so much.

**Comment by jerboaa** [comment] 2019-06-21 18:21
This is the same as #13. Once I know what we want to recommend we can fix it throughout.

https://github.com/red-hat-openjdk/docs/issues/13#issuecomment-502666027

**Comment by jerboaa** [comment] 2019-12-16 18:05
Closing as dupe of #13.

**Closed as completed by jerboaa** 2019-12-16 18:05 UTC
